version: '3.4'

services:
  ms-sublearn-back:
    image: almazic91/sub-learn-back:${BACK_IMAGE_VERSION}
    depends_on:
      - sublearn-db
      - ms-sublearn-translator
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sublearn-db:5432/sublearndb
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080

  sublearn-db:
    container_name: sublearn-db
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  ms-sublearn-translator:
    image: almazic91/sub-learn-translator:${TRANSLATOR_IMAGE_VERSION}
    ports:
      - 8081:8080
    environment:
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080
      YANDEX_DICT_URL:
      YANDEX_DICT_KEY:
      YANDEX_TRANSLATE_URL:
      YANDEX_TRANSLATE_KEY:

  sub-learn-telegram:
    image: almazic91/sub-learn-telegram:${TELEGRAM_IMAGE_VERSION}
    depends_on:
      - redis
    ports:
      - 8082:8080
    environment:
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080
      TG_TOKEN:
      TG_USERNAME:
      SPRING_REDIS_HOST: redis
      SUBLEARN_BACK_URL: http://ms-sublearn-back:8080/api

  redis:
    container_name: redis
    image: redis
    restart: always                  
